spring:
  thymeleaf: # Thymeleaf
    cache: false
    prefix: file:src/main/resources/templates/
  web:
    resources:
      static-locations: file:src/main/resources/static/
      cache:
        period: 0
logging:
  level:
    org.springframework: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG
supabase:
  projectId: jrwzknoawsweyfkpbizd
  anonKey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impyd3prbm9hd3N3ZXlma3BiaXpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NzY3MzQzMDAsImV4cCI6MTk5MjMxMDMwMH0.Bexiuih74rmWuRuzy126WxCwFVMvzb6BlbCQ8ZJyO1o
  databasePassword: Angles_Wrecker_Curtsy9
  jwtSecret: +jQOLR5dyMV98vgi62sdAHQ1ZPV7jmvhGqIzqKcAho0YjV6U+kaoVyAJgxATwDY/YX9cs43W/gTL5NHm55uWjg==
  successfulLoginRedirectPage: /account
  passwordRecoveryPage: /updatePassword
  unauthenticatedPage: /unauthenticated
  unauthorizedPage: /unauthorizedPage
  sslOnly: false

  public:
    get:
      - "/"
      - "/logout"
      - "/login"
      - "/403"
      - "/img/**"
      - "/error"
      - "/resetPassword"
      - "/unauthenticated"
      - "/unauthorized"
    post:
      - "/api/user/register"
      - "/api/user/login"
      - "/api/user/jwt"
      - "/api/user/sendPasswordResetEmail"
  roles:
    admin:
      get:
        - "/admin"
